package uk.co.i4software.poppie.census;

import lombok.Getter;

import static uk.co.i4software.poppie.census.FactName.*;

/**
 * (c) Copyright i4 Software Ltd. All Rights Reserved.
 *
 * @author David Barton
 * @since May 2015
 */
public enum FactType {

    SEX("Sex", TOTAL_MALES, TOTAL_FEMALES),

    AGES("Age", AGE_0_4, AGE_5_9, AGE_10_15, AGE_16_24, AGE_25_44, AGE_45_64, AGE_65_74, AGE_75_AND_OVER),

    HOUSEHOLDS("Households", IN_HOUSEHOLDS, IN_COMMUNAL_ESTABLISHMENTS, FULL_TIME_STUDENTS),

    ETHNIC_BACKGROUND("Ethnic Background", WHITE, BLACK_AND_MINORITY_ETHNIC),

    ETHNIC_BACKGROUND_WHITE("Ethnic Background: White", WHITE_BRITISH, WHITE_IRISH, WHITE_GYPSY_OR_IRISH_TRAVELLER,
            OTHER_WHITE),

    ETHNIC_BACKGROUND_MIXED("Ethnic Background: Mixed", WHITE_AND_BLACK_CARIBBEAN, WHITE_AND_BLACK_AFRICAN,
                            WHITE_AND_ASIAN, OTHER_MIXED),

    ETHNIC_BACKGROUND_ASIAN("Ethnic Background: Asian", INDIAN, PAKISTANI, BANGLADESHI, CHINESE, OTHER_ASIAN),

    ETHNIC_BACKGROUND_BLACK("Ethnic Background: Black", AFRICAN, CARIBBEAN, OTHER_BLACK),

    ETHNIC_BACKGROUND_OTHER("Ethnic Background: Other", ARAB, OTHER),

    COUNTRY_OF_BIRTH("Country of Birth", UNITED_KINGDOM, REPUBLIC_OF_IRELAND, EU_COUNTRIES, EU_ACCESSION_COUNTRIES,
            OTHER_COUNTRIES),

    RELIGION("Religion/Faith", CHRISTIAN, BUDDHIST, HINDU, JEWISH, MUSLIM, SIKH, OTHER_RELIGIONS, NO_RELIGION,
            RELIGION_NOT_STATED),

    LANGUAGES_SPOKEN("Languages Spoken", MAIN_LANGUAGE_ENGLISH, MAIN_LANGUAGE_NOT_ENGLISH),

    TIME_IN_UK("Time in UK", BORN_IN_UK, LESS_THAN_TWO_YEARS, TWO_TO_FIVE_YEARS, FIVE_TO_TEN_YEARS, MORE_THAN_TEN_YEARS),

    HEALTH("Health", VERY_GOOD_HEALTH, GOOD_HEALTH, FAIR_HEALTH, BAD_HEALTH, VERY_BAD_HEALTH),

    CARER_HOURS("Carer hours per week", ONE_NINETEEN, TWENTY_FORTYNINE, FIFTY_PLUS),

    ECONOMICS("Economics", FactName.ECONOMICALLY_ACTIVE, FactName.ECONOMICALLY_INACTIVE),

    ECONOMICALLY_ACTIVE("Economically Active", FULL_TIME_EMPLOYEES, PART_TIME_EMPLOYEES, SELF_EMPLOYED, UNEMPLOYED, FULL_TIME_STUDENT),

    ECONOMICALLY_INACTIVE("Economically Inactive", RETIRED, STUDENT, LOOKING_AFTER_HOME, LONG_TERM_SICK, ECONOMICALLY_INACTIVE_OTHER),

    QUALIFICATIONS("Qualifications", NO_QUALIFICATIONS, LEVEL_ONE, LEVEL_TWO, APPRENTICESHIP, LEVEL_THREE, LEVEL_FOUR,
            QUALIFICATIONS_OTHER),

    TRAVEL_TO_WORK("Travel to Work", WORK_FROM_HOME, LIGHT_RAIL, TRAIN, BUS, TAXI, MOTORCYCLE, DRIVING, PASSENGER, BICYCLE,
            FOOT, TRAVEL_TO_WORK_OTHER),

    EMPLOYMENT_HOURS("Employment Hours", PT_FIFTEEN_OR_LESS, PT_SIXTEEN_THIRTY, FT_THIRTYONE_FORTYEIGHT,
            FT_FORTYNINE_PLUS);






    @Getter private final String displayName;
    @Getter private final FactName[] factNames;

    FactType(String displayName, FactName... factNames) {
        this.factNames = factNames;
        this.displayName = displayName;
    }

}
