package uk.co.i4software.poppie.census;

import lombok.Getter;

import static uk.co.i4software.poppie.census.FactName.*;

/**
 * (c) Copyright i4 Software Ltd. All Rights Reserved.
 *
 * @author David Barton
 * @since May 2015
 */
public enum FactType {

    SEX("Sex", TOTAL_MALES, TOTAL_FEMALES),

    AGES("Age", AGE_0_4, AGE_5_9, AGE_10_15, AGE_16_24, AGE_25_44, AGE_45_64, AGE_65_74, AGE_75_AND_OVER),

    HOUSEHOLDS("Households", IN_HOUSEHOLDS, IN_COMMUNAL_ESTABLISHMENTS, FULL_TIME_STUDENTS),

    ETHNIC_BACKGROUND("Ethnic Background", WHITE, BLACK_AND_MINORITY_ETHNIC),

    ETHNIC_BACKGROUND_WHITE("Ethnic Background: White", WHITE_BRITISH, WHITE_IRISH, WHITE_GYPSY_OR_IRISH_TRAVELLER,
            OTHER_WHITE),

    ETHNIC_BACKGROUND_MIXED("Ethnic Background: Mixed", WHITE_AND_BLACK_CARIBBEAN, WHITE_AND_BLACK_AFRICAN,
            WHITE_AND_ASIAN, OTHER_MIXED),

    ETHNIC_BACKGROUND_ASIAN("Ethnic Background: Asian", INDIAN, PAKISTANI, BANGLADESHI, CHINESE, OTHER_ASIAN),

    ETHNIC_BACKGROUND_BLACK("Ethnic Background: Black", AFRICAN, CARIBBEAN, OTHER_BLACK),

    ETHNIC_BACKGROUND_OTHER("Ethnic Background: Other", ARAB, OTHER),

    COUNTRY_OF_BIRTH("Country of Birth", UNITED_KINGDOM, REPUBLIC_OF_IRELAND, EU_COUNTRIES, EU_ACCESSION_COUNTRIES,
            OTHER_COUNTRIES),

    RELIGION("Religion/Faith", CHRISTIAN, BUDDHIST, HINDU, JEWISH, MUSLIM, SIKH, OTHER_RELIGIONS, NO_RELIGION,
            RELIGION_NOT_STATED),

    LANGUAGES_SPOKEN("Languages Spoken", MAIN_LANGUAGE_ENGLISH, MAIN_LANGUAGE_NOT_ENGLISH),

    TIME_IN_UK("Time in UK", BORN_IN_UK, LESS_THAN_TWO_YEARS, TWO_TO_FIVE_YEARS, FIVE_TO_TEN_YEARS,
            MORE_THAN_TEN_YEARS),

    HEALTH("Health", VERY_GOOD_HEALTH, GOOD_HEALTH, FAIR_HEALTH, BAD_HEALTH, VERY_BAD_HEALTH),

    CARER_HOURS("Carer hours per week", ONE_NINETEEN, TWENTY_FORTYNINE, FIFTY_PLUS),

    ECONOMICS("Economics", FactName.ECONOMICALLY_ACTIVE, FactName.ECONOMICALLY_INACTIVE),

    ECONOMICALLY_ACTIVE("Economically Active", FULL_TIME_EMPLOYEES, PART_TIME_EMPLOYEES, SELF_EMPLOYED, UNEMPLOYED,
            FULL_TIME_STUDENT),

    ECONOMICALLY_INACTIVE("Economically Inactive", RETIRED, STUDENT, LOOKING_AFTER_HOME, LONG_TERM_SICK,
            ECONOMICALLY_INACTIVE_OTHER),

    QUALIFICATIONS("Qualifications", NO_QUALIFICATIONS, LEVEL_ONE, LEVEL_TWO, APPRENTICESHIP, LEVEL_THREE, LEVEL_FOUR,
            QUALIFICATIONS_OTHER),

    TRAVEL_TO_WORK("Travel to Work", WORK_FROM_HOME, LIGHT_RAIL, TRAIN, BUS, TAXI, MOTORCYCLE, DRIVING, PASSENGER,
            BICYCLE,
            FOOT, TRAVEL_TO_WORK_OTHER),

    EMPLOYMENT_HOURS("Employment Hours", PT_FIFTEEN_OR_LESS, PT_SIXTEEN_THIRTY, FT_THIRTYONE_FORTYEIGHT,
            FT_FORTYNINE_PLUS),

    OCCUPATION("Occupation Type", HIGHER_MANAGERIAL, LOWER_MANAGERIAL, INTERMEDIATE, SMALL_EMPLOYERS,
               LOWER_SUPERVISORY, SEMI_ROUTINE, ROUTINE, LONG_TERM_UNEMPLOYED, STUDENTS ),

    HOUSEHOLD_DWELLINGS("Household Dwellings", UNSHARED, SHARED),

    HOUSEHOLD_OCCUPATION("Household Occupied/Unoccupied", OCCUPIED, UNOCCUPIED),

    HOUSEHOLD_TYPE("Household Occupation Status", ONE_PERSON, MARRIED_WITH_CHILDREN, MARRIED_NO_CHILDREN,
            SAME_SEX_WITH_CHILDREN, SAME_SEX_NO_CHILDREN, LONE_PARENT_WITH_CHILDREN, LONE_PARENT_NO_CHILDREN,
            ALL_STUDENTS, MULTI_OTHER),

    HOUSING_TYPE("Housing Type", DETACHED, SEMI_DETACHED, TERRACED, PURPOSE_BUILT_FLATS, SHARED_HOUSE,
                 COMMERCIAL_BUILDING, CARAVAN),

    HOUSING_OWNERSHIP_STATUS("Housing Ownership Status", OWNED_OUTRIGHT, MORTGAGED, PART_OWNED, LOCAL_AUTHORITY,
            SOCIAL_OTHER, PRIVATE_LANDLORD, PRIVATE_OTHER, RENT_FREE),

    HOUSING_HEATING("Household Central Heating", NONE, GAS, ELECTRIC, OIL, SOLID_FUEL, OTHER_CENTRAL_HEATING,
            TWO_OR_MORE_TYPES),

    CARS_IN_HOUSEHOLD("Number of Cars in Household", NO_CARS, ONE_CAR, TWO_OR_MORE_CARS);


    @Getter private final String displayName;
    @Getter private final FactName[] factNames;

    FactType(String displayName, FactName... factNames) {
        this.factNames = factNames;
        this.displayName = displayName;
    }

}
